### ISSUE TITLE
Can't build images on top of images from private registries unless the 'deploy' parameter is set to true

### ISSUE THREAD

**Issue by AndrewASI** [CircleCI-Public/docker-orb#101]
### Orb version
2.0

### What happened
Docker login takes place only when 'deploy' parameter is set to true, so when I build an image `FROM private.registry/repo:tag` I can't only build it without pushing to the private registry. Also it's impossible to build `FROM private.registry1` and push to private.registry2

### Expected behavior
I expect that minimally there's another parameter like 'login-before-build' so I can login to the registry, but without pushing it afterwards.
Ideally I would like to have an option to have one registry to build images on top of images from it and the second registry to push to.

My regards,
Andrew

**Comment by EricRibeiro** [comment]
Hi @AndrewASI  👋 

> I can't only build it without pushing to the private registry.

Would you mind guiding me through this use case? I am not entirely sure why you want to build the image and not publish it. Also, isn't this something that you can accomplish by using the existing commands in your job?

I'll close the issue until I hear back from you, but happy to re-open to discuss it further.

**Comment by ezbercihk** [comment]
@EricRibeiro to piggyback on this, I see the the same behavior when I want to use the latest image as a cache source. In our workflows, we do builds for every commit to non-main branches where we do not necessarily want to push the built image to Docker Hub. Since docker login is not taking place because `deploy` is not set to `true`, it fails to pull the `latest` image and tries to use it as a cache source. Do you have any suggestions on how we can overcome this problem?

**Comment by ezbercihk** [comment]
Problem solved with the following, in case anyone else is running into this issue:

          before_build:
            - docker/check
